version: '3'

services:

  mqtt_broker:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: always

  mongo_mqtt_store:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo:/data/db
    ports:
      - '27017:27017'
    restart: always

  mqtt_subscriber:
    build: ./mqtt_subscriber_app
    entrypoint: ['sh','/app/entrypoint.sh']
    environment:
      - MQTT_BROKER_ADDR=mqtt_broker
      - MQTT_BROKER_PORT=1883
      - MONGO_URI=mongodb://admin:password@mongo_mqtt_store:27017/
      - MONDO_DB_NAME=mqtt_messages
      - MONGO_COLLECTION_NAME=messages
      - LOG_LEVEL=INFO
    volumes:
      - ./mqtt_subscriber_app/log:/app/log
    depends_on:
      - mqtt_broker
      - mongo_mqtt_store

  api:
    build: ./mqtt_reader_app
    entrypoint: ['sh','/app/entrypoint.sh']
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://admin:password@mongo_mqtt_store:27017/
      - MONDO_DB_NAME=mqtt_messages
      - MONGO_COLLECTION_NAME=messages
    depends_on:
      - mongo_mqtt_store

  mqtt_publisher:
    build: ./mqtt_publisher_app
    entrypoint: ['sh','/app/entrypoint.sh']
    environment:
      - MQTT_BROKER_ADDR=mqtt_broker
      - MQTT_BROKER_PORT=1883
    depends_on:
      - mqtt_broker

volumes:
  mongo:
