version: '3'

services:

  mqtt_broker:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: always
    networks:
      - shared_network

  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mqtt_store
    volumes:
      - mongo:/data/db
    ports:
      - '27017:27017'
    restart: always
    networks:
      - shared_network

volumes:
  mongo:

networks:
  shared_network:
    driver: bridge
