version: '3'

services:

  mqtt-broker:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: always

  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mqtt_store
    volumes:
      - mongo:/data/db
    ports:
      - '27017:27017'



  # mqtt_producer:
  #   build: ./mqtt_producer_app
  #   ports:
  #     - "6060:6060"
  #   depends_on:
  #     - db
  # mqtt_subscriber:
  #   build: ./mqtt_subscriber_app
  #   depends_on:
  #     - db
  #     - mqtt_producer

  # api:
  #   build: ./mqtt_reader_app
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - db
  #     - mqtt_producer
  #     - mqtt_subscriber

volumes:
  mongo:
