version: '3'

services:

  mqtt-broker:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"

  # db:
  #   image: mongo:3.4

  # mqtt_producer:
  #   build: ./mqtt_producer_app
  #   ports:
  #     - "6060:6060"
  #   depends_on:
  #     - db
  # mqtt_subscriber:
  #   build: ./mqtt_subscriber_app
  #   depends_on:
  #     - db
  #     - mqtt_producer

  # api:
  #   build: ./mqtt_reader_app
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - db
  #     - mqtt_producer
  #     - mqtt_subscriber
